name: Build docker images and publish to DockerHub

on:
  push:
  release:
    types: [published]
env:
  MOSQUITTO_VERSION_1: 1.6.14
  MOSQUITOO_VERSION_1_SUFFIX: -mosquitto_1.x
  MOSQUITTO_VERSION_2: 2.0.9
  MOSQUITOO_VERSION_2_SUFFIX: -mosquitto_2.x
  DOCKERHUB_REPO: mosquitto-go-auth
jobs:
  mosq_1:
    name: Build and publish with Mosquitto version 1.x
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set Mosquitto version
        run: sed -i 's/ARG MOSQUITTO_VERSION=1.6.14/ARG MOSQUITTO_VERSION=${{ env.MOSQUITTO_VERSION_1 }}/' Dockerfile
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push on release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${{ github.event.release.tag_name }}${{ env.MOSQUITOO_VERSION_1_SUFFIX }}
      -
        name: Build and push on push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:latest${{ env.MOSQUITOO_VERSION_1_SUFFIX }}
  mosq_2:
    name: Build and publish with Mosquitto version 2.x
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set Mosquitto version
        run: sed -i 's/ARG MOSQUITTO_VERSION=1.6.14/ARG MOSQUITTO_VERSION=${{ env.MOSQUITTO_VERSION_2 }}/' Dockerfile
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push on release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${{ github.event.release.tag_name }}${{ env.MOSQUITOO_VERSION_2_SUFFIX }}
      -
        name: Build and push on push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:latest${{ env.MOSQUITOO_VERSION_2_SUFFIX }}



